import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="Run XXX.")
    parser.add_argument('--data_path', nargs='?', default='../data', help='Input data path.')
    parser.add_argument('--seed', type=int, default=2023, help='random seed')
    parser.add_argument('--dataset',  default='ciao', help='Choose a dataset from {gowalla, amazon, tmall}')
    parser.add_argument('--conv_name', default='unigat', help='Conv layer name')
    parser.add_argument('--verbose', type=int, default=1, help='Interval of evaluation.')
    parser.add_argument('--save_model', type=bool, default=False, help='Whether to save')
    parser.add_argument('--epoch', type=int, default=1000, help='Number of epochs')
    parser.add_argument('--embed_size', type=int, default=1048, help='Embedding size.')
    parser.add_argument('--hidden_dim', type=int, default=1024, help='hidden dim size.')
    parser.add_argument('--output_dim', type=int, default=1000, help='The output dim size.')
    parser.add_argument('--n_batch', type=int, default=50, help='Number of mini-batches')
    parser.add_argument('--batch_size', type=int, default=8192, help='batch size')
    parser.add_argument('--train_num', type=int, default=15000, help='Number of training instances per epoch')
    parser.add_argument('--sample_num', type=int, default=50, help='Number of pos/neg samples for each instance')
    parser.add_argument('--lr', type=float, default=0.0006, help='Learning rate.')
    parser.add_argument('--emb_reg', type=float, default=2.5e-2, help='Regularizations.')
    parser.add_argument('--cen_reg', type=float, default=1e-1, help='Regularizations.')
    parser.add_argument('--cen_dis', type=float, default=5e-2, help='The distance between intentions.')
    parser.add_argument('--tau', type=float, default=0.2, help='The template parameter.')
    parser.add_argument('--ssl_reg', type=float, default=1e-2, help='Reg weight for ssl loss')
    parser.add_argument('--n_layers', type=int, default=2, help='Layer numbers.')
    parser.add_argument('--n_intents', type=int, default=6000, help='Number of latent intents')
    parser.add_argument('--temp', type=float, default=1, help='temperature in ssl loss')
    parser.add_argument('--show_step', type=int, default=1, help='Test every show_step epochs.')
    parser.add_argument('--Ks', nargs='?', default='[20, 40]', help='Metrics scale')
    parser.add_argument('--ui_k', type=int, default=10, help='Number of high order neighbors.')
    parser.add_argument('--kHop', type=int, default=1, help='Number of high order neighbors.')
    parser.add_argument('--num_workers', type=int, default=0, help='Number of workers.')
    parser.add_argument('--early_stop', type=int, default=70, help='Number of early stop epochs.')
    parser.add_argument('--intent_normalize', type=bool, default=False, help='intent_normalize.')
    parser.add_argument('--bias', type=bool, default=True, help='bias.')

    return parser.parse_args()
